---
- name: Configure network interfaces
  nmcli:
    conn_name: eth0
    ifname: eth0
    type: ethernet
    ip4: 192.168.1.100/24
    gw4: 192.168.1.1
    state: present

- name: Apply network configurations
  command: nmcli connection up eth0
